import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "./logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kiira College Butiki",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-[#d3d3d3] to-[#d3d3d3]`}
      >
        
        <NextUIProvider>
          <div className="flex">
            <div className="ml-auto mr-2">
              {!!session && (
                <div className="flex gap-4">
                  <Link href="/dashboard">Dashboards</Link>
                  <Logout />
                </div>
              )}
              {!session && <>
                <Link href="/auth/signin">Login</Link>
                <Link href="/auth/signup">SignUp</Link>
              </>}
            </div>
          </div>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
