import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import AuthProvider from "@/components/Providers";
import Appbar from "@/components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kiira College Butiki",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-[#d3d3d3] to-[#d3d3d3]`}
      >
        <AuthProvider>
          <NextUIProvider>
            <Appbar />
            {children}
          </NextUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
