import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "KCB Reports",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: ReactNode }) {
  return (
    <div className="w-full h-screen overflow-hidden p-0 m-0 fixed top-0 left-0">
      {children}
    </div>
  );
}
